name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install CUDA (Linux)
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.1.0'

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libcurl4-openssl-dev
          pip install cmake

      - name: Build (Linux)
        run: |
          mkdir build-linux
          cd build-linux
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: neuron_model_linux
          path: build-linux/

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install CUDA (Windows)
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.1.0'

      - name: Install dependencies (Windows)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install curl

      - name: Build (Windows)
        run: |
          mkdir build-windows
          cd build-windows
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: neuron_model_windows
          path: build-windows/

  test:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: List artifacts
        run: |
          echo "Build artifacts:"
          ls -la
          echo "Linux build:"
          ls -la neuron_model_linux/
          echo "Windows build:"
          ls -la neuron_model_windows/