# .github/workflows/qodana.yml
name: Qodana Code Quality
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          linter: jetbrains/qodana-clang:latest
          results-dir: ${{ runner.temp }}/qodana/results
          cache-dir: ${{ runner.temp }}/qodana/cache
          
          # 额外参数
          args: |
            --fail-threshold 0
          
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1824339855 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qodana-results
          path: ${{ runner.temp }}/qodana/results
          retention-days: 30
