name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - dev
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --image,jetbrains/qodana-clang:2025.2-eap
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1824339855 }}
